<script lang="ts">
	import { onMount } from 'svelte';
	import { drills } from '$lib/training/drills';
	import { makeShot, sideLabel } from '$lib/training/generator';
	import { PracticeScene } from '$lib/three/PracticeScene';
	import type { Drill, Hand, ShotSpec } from '$lib/training/types';
	let stage:HTMLDivElement, scene:PracticeScene;
	let hand:Hand='left', selected='fh-bh', interval=1200, speed=1, variance=1, seed=27, space=2, cueLead=500, marker=false, sound=true;
	let running=false, paused=false, countdown=0, count=0, startTime=0, elapsed=0, current:ShotSpec|null=null, next:ShotSpec|null=null, timer:ReturnType<typeof setTimeout>|null=null, phase:'ready'|'work'|'rest'|'done'='ready', work=45, rest=15, rounds=3, round=1;
	$: drill=drills.find(d=>d.id===selected)??drills[0];
	$: moveScale=space===1?'compact steps':space===2?'normal steps':'full steps';
	function save(){localStorage.setItem('rallyroom-v2',JSON.stringify({hand,selected,interval,speed,variance,seed,space,cueLead,marker,sound,work,rest,rounds}))}
	function choose(d:Drill){selected=d.id;interval=d.defaultInterval;save()}
	function beep(freq=620,d=.08){if(!sound)return;const C=window.AudioContext;const a=new C(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.1,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+d)}
	async function start(){if(running)return;save();running=true;paused=false;phase='ready';count=0;round=1;startTime=Date.now();for(const n of [3,2,1]){countdown=n;beep(420+n*80);await new Promise(r=>setTimeout(r,700));if(!running)return}countdown=0;phase='work';schedule(true)}
	function schedule(first=false){if(!running||paused)return;const age=(Date.now()-startTime)/1000;elapsed=Math.floor(age);if(age>=round*(work+rest)-rest){if(round>=rounds){finish();return}phase='rest';timer=setTimeout(()=>{round++;phase='work';schedule(true)},rest*1000);return}
		const i=count;next=makeShot(drill,i,hand,variance,seed,speed);scene.prepare(next);timer=setTimeout(()=>{if(!running||paused||!next)return;current=next;scene.feed(current,marker);count++;beep(current.feed==='backspin'?380:720,.055);timer=setTimeout(()=>schedule(),Math.max(350,interval-cueLead))},first?cueLead:cueLead)}
	function toggle(){if(!running){start();return}paused=!paused;if(timer)clearTimeout(timer);if(!paused)schedule(true)}
	function finish(){running=false;paused=false;phase='done';if(timer)clearTimeout(timer);elapsed=Math.floor((Date.now()-startTime)/1000)}
	function contact(s:ShotSpec){current=s;beep(980,.04)}
	function key(e:KeyboardEvent){if(e.code==='Space'){e.preventDefault();toggle()}if(e.key==='Escape'&&document.fullscreenElement)document.exitFullscreen()}
	function full(){document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()}
	onMount(()=>{try{const p=JSON.parse(localStorage.getItem('rallyroom-v2')||'{}');hand=p.hand??hand;selected=p.selected??selected;interval=p.interval??interval;speed=p.speed??speed;variance=p.variance??variance;seed=p.seed??seed;space=p.space??space;cueLead=p.cueLead??cueLead;marker=p.marker??marker;sound=p.sound??sound}catch{};
		try{scene=new PracticeScene(stage,contact)}catch{stage.classList.add('fallback')};const ro=new ResizeObserver(()=>scene?.resize());ro.observe(stage);window.addEventListener('keydown',key);return()=>{if(timer)clearTimeout(timer);ro.disconnect();scene?.dispose();window.removeEventListener('keydown',key)}})
</script>

<svelte:head><title>Rally Room — Shadow Practice</title><meta name="description" content="Table tennis footwork and stroke shadow practice."/></svelte:head>
<main class:session={running}>
	<header><a class="brand" href="/" aria-label="Rally Room home"><span>RR</span><b>RALLY ROOM</b><small>SHADOW PRACTICE</small></a><div class="header-actions"><button class="icon" onclick={()=>sound=!sound} aria-label="Toggle sound">{sound?'SOUND ON':'MUTED'}</button><button class="icon" onclick={full}>⛶ FULLSCREEN</button></div></header>
	<section class="hero">
		<div class="visual" bind:this={stage} aria-label="3D table tennis practice view">
			<div class="scan"></div><div class="status"><i class:live={running}></i>{paused?'PAUSED':phase==='rest'?`REST · ${rest}s`:running?`ROUND ${round}/${rounds}`:'READY'}</div>
			{#if countdown}<div class="countdown"><small>GET SET</small>{countdown}</div>{/if}
			{#if current && running}<div class="shot-cue"><small>NOW</small><strong>{current.response}</strong><span>{current.cue}</span></div>{/if}
			{#if next && running}<div class="next"><small>NEXT</small><b>{sideLabel(next.zone,hand)}</b><span>{next.feed}</span></div>{/if}
			<div class="baseline"><span>YOUR SIDE</span><b>{moveScale.toUpperCase()}</b></div>
			<div class="fallback-copy"><b>3D unavailable</b><span>Use the target and timing cues to continue practicing.</span></div>
		</div>
		<div class="sessionbar"><div><small>DRILL</small><b>{drill.name}</b></div><div><small>FEEDS</small><b>{count}</b></div><div><small>TEMPO</small><b>{(interval/1000).toFixed(1)}s</b></div><button class="primary" onclick={toggle}>{running?(paused?'RESUME':'PAUSE'):'START PRACTICE'} <kbd>SPACE</kbd></button>{#if running}<button class="stop" onclick={finish}>END</button>{/if}</div>
	</section>

	<section class="setup" aria-label="Practice setup">
		<div class="intro"><small>BUILD YOUR SESSION</small><h1>Move first.<br/><em>Strike on time.</em></h1><p>Read the opponent's racket, move to the ball and shadow your stroke as it bounces. No camera. No scoring. Just deliberate repetitions.</p></div>
		<div class="controls">
			<div class="seg"><span class="group-label">PLAYING HAND</span><button class:active={hand==='left'} onclick={()=>hand='left'}>Left handed</button><button class:active={hand==='right'} onclick={()=>hand='right'}>Right handed</button></div>
			<div class="mode-tabs"><button class:active={drill.category==='Footwork'} onclick={()=>choose(drills[0])}>01 FOOTWORK</button><button class:active={drill.category==='Stroke'} onclick={()=>choose(drills[10])}>02 STROKES</button></div>
			<div class="drill-list">{#each drills.filter(d=>d.category===drill.category) as d,i}<button class:active={d.id===selected} onclick={()=>choose(d)}><span>{String(i+1).padStart(2,'0')}</span><div><b>{d.name}</b><small>{d.description}</small></div><i>{d.pattern.map(p=>p.response.replace(' pivot','↗')).join(' · ')}</i></button>{/each}</div>
		</div>
		<aside>
			<h2>Session settings</h2>
			<label>Feed interval <output>{(interval/1000).toFixed(1)} sec</output><input type="range" min="800" max="3000" step="50" bind:value={interval}/><small>Default: continuous rally pace</small></label>
			<label>Ball speed <output>{speed<.9?'Controlled':speed>1.1?'Fast rally':'Continuous rally'}</output><input type="range" min=".75" max="1.25" step=".05" bind:value={speed}/><small>Changes flight time, not feed rhythm</small></label>
			<label>Pattern variance <output>{variance==0?'Exact':variance==1?'Gentle':'Match-like'}</output><input type="range" min="0" max="2" step="1" bind:value={variance}/><small>Pattern order never changes</small></label>
			<label>Home space <output>{space==1?'Small':space==2?'Medium':'Large'}</output><input type="range" min="1" max="3" step="1" bind:value={space}/><small>Scales your shadow steps, not the table</small></label>
			<label>Racket cue lead <output>{cueLead/1000}s</output><input type="range" min="300" max="1000" step="50" bind:value={cueLead}/></label>
			<div class="inline"><label>Work <input type="number" min="15" max="180" bind:value={work}/> sec</label><label>Rest <input type="number" min="5" max="60" bind:value={rest}/> sec</label><label>Rounds <input type="number" min="1" max="10" bind:value={rounds}/></label></div>
			<div class="toggles"><label><input type="checkbox" bind:checked={marker}/> Show landing marker</label><label><input type="checkbox" bind:checked={sound}/> Sound cues</label></div>
			{#if selected==='controlled'}<label>Reproducible seed <input type="number" bind:value={seed}/></label>{/if}
		</aside>
	</section>
	{#if phase==='done'}<div class="modal" role="dialog"><div><small>SESSION COMPLETE</small><h2>Good work.</h2><p><b>{count}</b> feeds · <b>{Math.floor(elapsed/60)}:{String(elapsed%60).padStart(2,'0')}</b> · {drill.name} · {(interval/1000).toFixed(1)}s tempo</p><button class="primary" onclick={()=>phase='ready'}>BACK TO SETUP</button></div></div>{/if}
</main>

<style>
	:global(*){box-sizing:border-box} :global(body){margin:0;background:#061017;color:#eaf4f1;font-family:Inter,ui-sans-serif,system-ui,sans-serif} :global(button),:global(input){font:inherit} main{min-height:100vh;background:radial-gradient(circle at 70% 5%,#12303a 0,transparent 30%)}
	header{height:72px;display:flex;align-items:center;justify-content:space-between;padding:0 4vw;border-bottom:1px solid #ffffff18}.brand{color:inherit;text-decoration:none;display:grid;grid-template-columns:42px auto;grid-template-rows:1fr 1fr;column-gap:12px}.brand span{grid-row:1/3;background:#ddff48;color:#071017;font-weight:950;display:grid;place-items:center}.brand b{font-size:14px;align-self:end;letter-spacing:.15em}.brand small{color:#8da3a5;font-size:9px;letter-spacing:.22em}.header-actions{display:flex;gap:8px}.icon,.stop{background:#ffffff08;border:1px solid #ffffff22;color:#b9cbcc;padding:10px 14px;border-radius:5px;font-size:11px;font-weight:800;letter-spacing:.08em;cursor:pointer}
	.hero{padding:24px 4vw 0}.visual{height:min(58vh,640px);min-height:380px;position:relative;overflow:hidden;border-radius:10px 10px 0 0;background:#07131b}.visual :global(canvas){width:100%;height:100%;display:block}.scan{position:absolute;inset:0;pointer-events:none;background:linear-gradient(90deg,transparent 49.9%,#ffffff08 50%,transparent 50.1%)}.status{position:absolute;top:22px;left:24px;background:#071017bb;padding:8px 11px;border-radius:4px;font-size:10px;font-weight:900;letter-spacing:.13em}.status i{display:inline-block;width:7px;height:7px;background:#748386;border-radius:50%;margin-right:8px}.status i.live{background:#ddff48;box-shadow:0 0 10px #ddff48}.next{position:absolute;top:22px;right:24px;text-align:right;background:#071017bb;padding:10px 13px;border-radius:5px}.next small,.shot-cue small{display:block;color:#ddff48;font-size:9px;letter-spacing:.2em}.next b{display:block;font-size:18px}.next span{font-size:11px;color:#91a5a7;text-transform:uppercase}.shot-cue{position:absolute;left:50%;bottom:68px;transform:translateX(-50%);text-align:center;text-shadow:0 2px 8px #000}.shot-cue strong{display:block;font-size:clamp(32px,5vw,70px);line-height:1}.shot-cue span{font-size:13px}.countdown{position:absolute;inset:0;display:grid;place-content:center;text-align:center;background:#06101755;font-size:150px;font-weight:950;color:#ddff48}.countdown small{font-size:12px;letter-spacing:.3em;color:white}.baseline{position:absolute;bottom:18px;left:20px;right:20px;display:flex;justify-content:space-between;font-size:9px;letter-spacing:.2em;color:#83a0a2}.fallback-copy{display:none}.visual:global(.fallback) .fallback-copy{display:flex;position:absolute;inset:0;align-items:center;justify-content:center;flex-direction:column}.sessionbar{min-height:82px;background:#0d2028;display:flex;align-items:center;gap:3vw;padding:12px 18px;border-radius:0 0 10px 10px}.sessionbar>div{display:flex;flex-direction:column;min-width:80px}.sessionbar small,.intro>small{font-size:9px;letter-spacing:.18em;color:#7f999b}.sessionbar b{font-size:14px}.primary{margin-left:auto;background:#ddff48;color:#071017;border:0;border-radius:5px;padding:16px 22px;font-weight:950;cursor:pointer;letter-spacing:.04em}.primary kbd{margin-left:15px;font-size:9px;opacity:.6}
	.setup{display:grid;grid-template-columns:.8fr 1.6fr .9fr;gap:5vw;padding:80px 4vw}.intro h1{font-size:clamp(38px,4vw,64px);line-height:.98;margin:15px 0 24px;letter-spacing:-.045em}.intro em{font-style:normal;color:#ddff48}.intro p{color:#93a7a9;line-height:1.65;max-width:400px}.seg .group-label{display:block;font-size:9px;color:#799294;letter-spacing:.18em;margin-bottom:8px}.seg button,.mode-tabs button{border:1px solid #ffffff1a;background:#ffffff05;color:#98abad;padding:11px 15px;font-size:11px;font-weight:800;cursor:pointer}.seg button.active,.mode-tabs button.active{background:#e6f5f1;color:#071017}.mode-tabs{display:flex;margin:35px 0 12px;border-bottom:1px solid #ffffff1a}.mode-tabs button{border:0;background:transparent}.mode-tabs button.active{color:#ddff48;background:transparent;border-bottom:2px solid #ddff48}.drill-list{display:grid;gap:6px}.drill-list button{width:100%;display:grid;grid-template-columns:30px 1fr auto;align-items:center;text-align:left;color:#b9c9c9;border:1px solid transparent;background:#ffffff05;padding:12px;cursor:pointer;border-radius:5px}.drill-list button.active{border-color:#ddff48;background:#193039}.drill-list span{font-size:10px;color:#728a8c}.drill-list b{display:block;font-size:13px}.drill-list small{display:block;color:#83999b;margin-top:3px}.drill-list i{font-size:10px;color:#ddff48;font-style:normal}aside{background:#0d2028;padding:24px;border-radius:8px;align-self:start}aside h2{margin-top:0;font-size:18px}aside>label{display:block;font-size:11px;font-weight:800;margin:19px 0}output{float:right;color:#ddff48}input[type=range]{display:block;width:100%;accent-color:#ddff48;margin:10px 0}label small{display:block;color:#728a8c;font-weight:400}.inline{display:flex;gap:8px}.inline label{font-size:10px}.inline input,input[type=number]{width:58px;background:#061017;color:white;border:1px solid #ffffff22;border-radius:3px;padding:7px}.toggles label{display:block;font-size:11px;margin:12px 0}.toggles input{accent-color:#ddff48}.modal{position:fixed;inset:0;background:#02080bd9;display:grid;place-items:center;z-index:10}.modal>div{background:#10252d;padding:50px;text-align:center;border:1px solid #ffffff22;border-radius:9px}.modal small{color:#ddff48;letter-spacing:.2em}.modal h2{font-size:46px;margin:10px}.modal .primary{margin:15px 0 0}
	@media(max-width:900px){.setup{grid-template-columns:1fr 1.5fr}.intro{grid-column:1/-1}.setup aside{grid-column:1}.controls{grid-column:2;grid-row:2}.visual{height:52vh}.sessionbar>div:nth-child(2){display:none}}
	@media(max-width:620px){header{height:58px}.header-actions .icon:first-child{display:none}.hero{padding:10px 10px 0}.visual{height:54vh;min-height:340px}.sessionbar{gap:8px;flex-wrap:wrap}.sessionbar>div{min-width:60px}.sessionbar>div:first-child{flex:1}.sessionbar .primary{order:4;width:100%;margin:0}.setup{display:flex;flex-direction:column;padding:50px 16px}.controls{order:2}.setup aside{order:1}.drill-list i{display:none}.shot-cue{bottom:50px}.next{right:12px}.intro h1{font-size:45px}.stop{position:absolute;top:75px;right:16px}}
	.session .setup{display:none}.session header{height:52px}.session .hero{padding-top:8px}.session .visual{height:calc(100vh - 150px);max-height:none} @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}.countdown{transition:none}}
</style>
